- name: Creating nfs export directories
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"

- name: Creating /etc/exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  # The notification event will be sended to 
  # the handler with the corresponding name 
  # in the handlers folder
  notify: reload_nfs

- name: Start nfs service.
  service: "name=nfs-kernel-server state=started enabled=yes"
  when: nfs_exports|length

# Master should be rebooted manually
# - name: Reboot and wait for reboot to complete
#   reboot: